local status, readline = pcall(require, 'readline')
if (not status) then return end
vim.keymap.set('!', "<C-f>", readline.forward_word)
vim.keymap.set('!', "<C-b>", readline.backward_word)
vim.keymap.set('!', "<C-a>", readline.beginning_of_line)
vim.keymap.set('!', "<C-e>", readline.end_of_line)
vim.keymap.set('!', "<M-d>", readline.kill_word)
vim.keymap.set('!', "<C-w>", readline.unix_word_rubout)
vim.keymap.set('!', "<C-k>", readline.kill_line)
vim.keymap.set('!', "<C-u>", readline.backward_kill_line)
