: ${FAST_HIGHLIGHT_STYLES[safaridefault]:=none}
: ${FAST_HIGHLIGHT_STYLES[safariunknown-token]:=fg=red,bold}
: ${FAST_HIGHLIGHT_STYLES[safarireserved-word]:=fg=150}
: ${FAST_HIGHLIGHT_STYLES[safarialias]:=fg=185}
: ${FAST_HIGHLIGHT_STYLES[safarisuffix-alias]:=fg=185}
: ${FAST_HIGHLIGHT_STYLES[safaribuiltin]:=fg=185}
: ${FAST_HIGHLIGHT_STYLES[safarifunction]:=fg=185}
: ${FAST_HIGHLIGHT_STYLES[safaricommand]:=fg=185}
: ${FAST_HIGHLIGHT_STYLES[safariprecommand]:=fg=185}
: ${FAST_HIGHLIGHT_STYLES[safaricommandseparator]:=none}
: ${FAST_HIGHLIGHT_STYLES[safarihashed-command]:=fg=185}
: ${FAST_HIGHLIGHT_STYLES[safaripath]:=fg=187}
: ${FAST_HIGHLIGHT_STYLES[safaripath_pathseparator]:=}
: ${FAST_HIGHLIGHT_STYLES[safariglobbing]:=fg=180}
: ${FAST_HIGHLIGHT_STYLES[safariglobbing-ext]:=fg=184}
: ${FAST_HIGHLIGHT_STYLES[safarihistory-expansion]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[safarisingle-hyphen-option]:=fg=152}
: ${FAST_HIGHLIGHT_STYLES[safaridouble-hyphen-option]:=fg=152}
: ${FAST_HIGHLIGHT_STYLES[safariback-quoted-argument]:=none}
: ${FAST_HIGHLIGHT_STYLES[safarisingle-quoted-argument]:=fg=151}
: ${FAST_HIGHLIGHT_STYLES[safaridouble-quoted-argument]:=fg=151}
: ${FAST_HIGHLIGHT_STYLES[safaridollar-quoted-argument]:=fg=151}
: ${FAST_HIGHLIGHT_STYLES[safariback-or-dollar-double-quoted-argument]:=fg=153}
: ${FAST_HIGHLIGHT_STYLES[safariback-dollar-quoted-argument]:=fg=153}
: ${FAST_HIGHLIGHT_STYLES[safariassign]:=none}
: ${FAST_HIGHLIGHT_STYLES[safariredirection]:=none}
: ${FAST_HIGHLIGHT_STYLES[safaricomment]:=fg=black,bold}
: ${FAST_HIGHLIGHT_STYLES[safarivariable]:=none}
: ${FAST_HIGHLIGHT_STYLES[safarimathvar]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[safarimathnum]:=fg=187}
: ${FAST_HIGHLIGHT_STYLES[safarimatherr]:=fg=red}
: ${FAST_HIGHLIGHT_STYLES[safariassign-array-bracket]:=fg=185}
: ${FAST_HIGHLIGHT_STYLES[safarifor-loop-variable]:=none}
: ${FAST_HIGHLIGHT_STYLES[safarifor-loop-number]:=fg=187}
: ${FAST_HIGHLIGHT_STYLES[safarifor-loop-operator]:=fg=151}
: ${FAST_HIGHLIGHT_STYLES[safarifor-loop-separator]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[safariexec-descriptor]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[safarihere-string-tri]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[safarihere-string-text]:=bg=19}
: ${FAST_HIGHLIGHT_STYLES[safarihere-string-var]:=fg=153,bg=19}
: ${FAST_HIGHLIGHT_STYLES[safarisecondary]:=zdharma}
: ${FAST_HIGHLIGHT_STYLES[safaricase-input]:=fg=185}
: ${FAST_HIGHLIGHT_STYLES[safaricase-parentheses]:=fg=116}
: ${FAST_HIGHLIGHT_STYLES[safaricase-condition]:=bg=19}
: ${FAST_HIGHLIGHT_STYLES[safaricorrect-subtle]:=bg=55}
: ${FAST_HIGHLIGHT_STYLES[safariincorrect-subtle]:=bg=52}
: ${FAST_HIGHLIGHT_STYLES[safarisubtle-bg]:=bg=18}
: ${FAST_HIGHLIGHT_STYLES[safaripath-to-dir]:=fg=187,underline}
: ${FAST_HIGHLIGHT_STYLES[safaripaired-bracket]:=bg=blue}
: ${FAST_HIGHLIGHT_STYLES[safaribracket-level-1]:=fg=178}
: ${FAST_HIGHLIGHT_STYLES[safaribracket-level-2]:=fg=148}
: ${FAST_HIGHLIGHT_STYLES[safaribracket-level-3]:=fg=141}
: ${FAST_HIGHLIGHT_STYLES[safariglobal-alias]:=bg=19}
: ${FAST_HIGHLIGHT_STYLES[safarisubcommand]:=fg=150}
: ${FAST_HIGHLIGHT_STYLES[safarisingle-sq-bracket]:=fg=185}
: ${FAST_HIGHLIGHT_STYLES[safaridouble-sq-bracket]:=fg=185}
: ${FAST_HIGHLIGHT_STYLES[safaridouble-paren]:=fg=150}
: ${FAST_HIGHLIGHT_STYLES[safarioptarg-string]:=fg=151}
: ${FAST_HIGHLIGHT_STYLES[safarioptarg-number]:=fg=187}
: ${FAST_HIGHLIGHT_STYLES[safarirecursive-base]:=fg=183}
