#!/bin/bash

cd `dirname "${BASH_SOURCE[0]}"`

source ./markup
source ./popup

source ./popup_updates
source ./popup_volume

# kill existing processes
ps ax | grep "$(pwd)/daemon" | egrep -v "$$" | awk '{print $1}' | xargs -t kill >/dev/null 2>&1

watch_volume &
watch_updates &

# kill the script if it's already running
kill $(pgrep -f 'python3 ./i3ws') >/dev/null 2>&1
python3 ./i3ws &

wait # will never happen
