#!/usr/bin/python

import i3ipc # i3ipc
from uuid import uuid4
from subprocess import Popen

uuid = str(uuid4())

def notify(self, event):
    t=("eventc notification workspace {} -d".format(uuid)).split()
    msg="title='{}'".format("lost\ngost\nkek pep lol")
    t.append(msg)
    Popen(t)

i3 = i3ipc.Connection()
i3.on('workspace::focus', notify)
i3.main()
