#!/bin/bash

KEYBOARD_ICON=''

status_keyboard(){
	layout=`setxkbmap -query | awk '/layout/ {print $2}'`
	markup $KEYBOARD_ICON $layout
}

watch_keyboard(){
	# TODO, might need to use python
	echo
}
