#!/bin/bash

VOLUME_ICON_SPEAKER=''
VOLUME_ICON_HEADPHONE=''

VOLUME_COLOR_URGENT='RRR'
VOLUME_COLOR_ACTIVE='7E4'
VOLUME_COLOR_MUTED='E44'

VOLUME_UUID=`uuidgen`

status_volume(){
	sinkName=`pacmd stat | awk -F': ' '/^Default sink name: / {print $2}'`

	while read -r line; do
		case $line in
			state:\ RUNNING)
				color=$VOLUME_COLOR_ACTIVE ;;
			muted:\ yes)
				color=$VOLUME_COLOR_URGENT ;;
			active\ port:\ *headphone*)
				icon=$VOLUME_ICON_HEADPHONE ;;
			active\ port:*)
				icon=$VOLUME_ICON_SPEAKER ;;
			volume:*)
				read -r _ _ _ _ volume _ <<< "$line" ;;
		esac
	done < <(pacmd list-sinks | sed '/'"$sinkName"'/,/index:/!d')

	markup $icon $volume $color
}

watch_volume(){
	pactl subscribe 2>/dev/null | {
		while true; do
			{
				read -r event || break
				if ! grep "on card\|sink" <<< "$event"; then
					# avoid double events
					continue
				fi
			} &>/dev/null

			status="`status_volume`"
			popup "${status//#RRR/#$VOLUME_COLOR_MUTED}" $VOLUME_UUID
		done
	}
}
