#!/bin/bash

VPN_ICON=''

VPN_COLOR_URGENT='RRR'
VPN_COLOR_CONNECTED='7E4'
VPN_COLOR_DISCONNECTED='E44'

VPN_UUID=`uuidgen`

status_vpn(){
	systemctl is-active openvpn-client@home >/dev/null 2>&1
	if (($? == 0)); then
		markup $VPN_ICON 'Home' $VPN_COLOR_CONNECTED
		return
	fi

	pidof openconnect >/dev/null 2>&1
	if (($? == 0)); then
		markup $VPN_ICON 'NTNU' $VPN_COLOR_CONNECTED
		return
	fi

	markup $VPN_ICON 'None' $VPN_COLOR_URGENT
}

watch_vpn(){
	journalctl -fu systemd-networkd | while read -r event; do
		status=`status_vpn`
		[[ -n "$status" ]] && popup "${status//#RRR/#$VPN_COLOR_DISCONNECTED}" $VPN_UUID
	done
}
