#!/bin/bash

# attempt to clear queue first
eventdctl nd dismiss all topleft
if (($? != 50)); then
	# queue was not empty, user tried to remove the popup, so bail
	exit 0
fi

cd `dirname "${BASH_SOURCE[0]}"`

source ./markup
source ./popup

source ./popup_clock
source ./popup_date
source ./popup_battery
source ./popup_network
source ./popup_vpn
source ./popup_volume
source ./popup_keyboard
source ./popup_updates

URGENT_COLOR=E44

status=()
status+=("$(status_clock)")
status+=("$(status_date)")
status+=("$(status_battery)")
status+=("$(status_network)")
status+=("$(status_vpn)")
status+=("$(status_volume)")
status+=("$(status_keyboard)")

# clear out empty indices
for i in "${!status[@]}"; do
	[[ -z "${status[$i]}" ]] && unset status[$i]
done

str="`printf "%s\n" "${status[@]}"`"
str="${str//#[0-9A-F][0-9A-F][0-9A-F]/#777}"
str="${str//#RRR/#$URGENT_COLOR}"

popup "$str" '' '' info

# a separate popup for updates, as it takes time to fetch data
update_status="$(status_updates)"
if [[ -n "$update_status" ]]; then
	popup "${update_status//#RRR/#$URGENT_COLOR}" '' '' info
fi
