[buildPlans.iosevka]
family = "Iosevka"
spacing = "term"
serifs = "sans"

[buildPlans.iosevka.variants.design]
turn-v = "curly"
capital-b = "standard"
capital-d = "more-rounded"
capital-g = "toothed"
capital-i = "short-serifed"
capital-j = "serifed-both-sides"
capital-k = "curly"
capital-l = "motion-serifed"
capital-m = "flat-bottom"
capital-q = "straight"
capital-r = "curly"
capital-y = "curly"
capital-z = "curly-with-horizontal-crossbar"
a = "doublestorey"
b = "toothed"
d = "toothed"
e = "flat-crossbar"
f = "serifless"
g = "doublestorey"
h = "straight"
i = "serifed-tailed"
j = "serifed"
k = "straight"
l = "serifed"
m = "normal"
n = "straight"
p = "eared"
q = "straight"
r = "serifless"
t = "standard"
u = "toothed"
v = "straight"
w = "straight"
x = "straight"
y = "straight"
z = "standard"
lambda = "curly"
cyrl-capital-u = "cursive-flat-hook"
one = "base-long-top-serif"
two = "curly-neck"
three = "flattop"
four = "semi-open-non-crossing"
six = "straight-bar"
seven = "crossbar"
eight = "crossing"
nine = "open-contour"
asterisk = "hexlow"
underscore = "low"
paragraph-sign = "low"
paren = "normal"
brace = "curly"
number-sign = "upright"
at = "fourfold"
dollar = "through"
percent = "rings"
lig-ltgteq = "slanted"
ascii-single-quote = "straight"
ascii-grave = "straight"

  [buildPlans.iosevka.ligations]
  inherits = "fsharp"
