api.nvim_command('omap <C-b> <Left>')
api.nvim_command('omap <C-e> <End>')
api.nvim_command('inoremap <M-x>b <C-o>:Buffers<CR>')
api.nvim_command('nnoremap <M-x>b <C-o>:Buffers<CR>')
api.nvim_command('inoremap <C-f> <C-o>e<Right>')
api.nvim_command('inoremap <C-b> <S-Left>')
api.nvim_command('inoremap <C-d> <C-O>dw')
api.nvim_command('onoremap <C-f> e<Right>')
api.nvim_command('inoremap <silent> <c-a> <esc>I')
api.nvim_command('cnoremap <M-a> <home>')
api.nvim_command('cnoremap <M-e> <end>')
api.nvim_command('cnoremap <M-b> <left>')
api.nvim_command('cnoremap <M-p> <up>')
api.nvim_command('cnoremap <M-n> <down>')
api.nvim_command('cnoremap <C-d> <S-Right><C-w>')
api.nvim_command('cnoremap <M-y> <C-r><C-o>"')
api.nvim_command('cnoremap <C-f> <S-Right>')
