#--[ Main ]--------------------------------------------------------------------------
[[plugins]]
repo = 'thinca/vim-quickrun' # run a bunch of text
[[plugins]]
repo = 'Shougo/neomru.vim' # add neomru source
[[plugins]]
repo = 'itchyny/lightline.vim' # lightline statusline
[[plugins]]
repo = 'maximbaz/lightline-ale' # lightline ale mod
[[plugins]]
repo = 'justinmk/vim-dirvish' # netrw replacement
[[plugins]]
repo = 'bounceme/remote-viewer' # dirvish remote-viewer
[[plugins]]
repo = 'kristijanhusak/vim-dirvish-git' # git support for divish
[[plugins]]
repo = 'Shougo/defx.nvim' # better file-manager for nvim
# --[ Edit ]-------------------------------------------------------------------------------
[[plugins]]
repo = 'sbdchd/neoformat' # universal formatter
[[plugins]]
repo = 'SirVer/ultisnips.git' # Snippets with ycm compatibility
[[plugins]]
repo = 'tpope/vim-unimpaired.git' # good mappings and toggles
[[plugins]]
repo = 'tpope/vim-repeat' # dot for everything
[[plugins]]
repo = 'Raimondi/delimitMate' # autopair ([]{})
[[plugins]]
repo = 'tpope/vim-surround' # new commands to vim for ({}[]''# # <>)
[[plugins]]
repo = 'junegunn/vim-easy-align' # use easy-align, instead of tabular
[[plugins]]
repo = 'machakann/vim-swap' # swap with emacs
#--[ Additions ]--------------------------------------------------------------------------
[[plugins]]
repo = 'kopischke/vim-fetch' # vim path/to/file.ext:12:3
[[plugins]]
repo = 'FooSoft/vim-argwrap' # vim arg wrapper
[[plugins]]
repo = 'Valloric/ListToggle.git' # toggle quickfix and location list <leader>l by def
[[plugins]]
repo = 'lyokha/vim-xkbswitch.git' # Autoswitch on <esc> with libxkb needs xkb-switch-git to run
[[plugins]]
repo = 'echuraev/translate-shell.vim' # translate in nvim
# --[ Rice ]-------------------------------------------------------------------------------
[[plugins]]
repo = 'luochen1990/rainbow' # rainbow parentheses
[[plugins]]
repo = 'thinca/vim-qfreplace.git' # visual replace for multiple files
[[plugins]]
repo = 'tpope/vim-eunuch.git' # for SudoWrite, Locate, Find etc
[[plugins]]
repo = 'tpope/vim-abolish' # for different case coersion
[[plugins]]
repo = 'TaDaa/vimade' # dynamic syntax highlighting
#--[ Search ]-----------------------------------------------------------------------------
[[plugins]]
repo = 'junegunn/fzf' # fzf itself
build = './install'
merged = 0
[[plugins]]
repo = 'junegunn/fzf.vim' #  fzf vim bindings
depends = 'fzf'
[[plugins]]
repo = 'sjbach/lusty.git' # file/buffer explorer
[[plugins]]
repo = 'dyng/ctrlsf.vim' # interactive vim-grep
[[plugins]]
repo = 'jremmen/vim-ripgrep' # ripgrep binding
[[plugins]]
repo = 'wsdjeg/FlyGrep.vim' # async grep
# --[ Docs ]------------------------------------------------------------------------------
[[plugins]]
repo = 'thinca/vim-ref.git' # integrated reference viewer man/perldoc etc
# --[ Dev ]-------------------------------------------------------------------------------
[[plugins]]
repo = 'chrisbra/vim-diff-enhanced.git' # patience diff
[[plugins]]
repo = 'tpope/vim-dispatch.git' # provide async build via tmux
[[plugins]]
repo = 'radenling/vim-dispatch-neovim' # advanced neovim support
[[plugins]]
repo = 'w0rp/ale' # ale as linter
[[plugins]]
repo = 'tomtom/tcomment_vim' # commenter plugin
[[plugins]]
repo = 'tpope/vim-endwise' # to insert endif for if, end for begin and so on
[[plugins]]
repo = 'dbakker/vim-projectroot' # better rooter
[[plugins]]
repo = 'derekwyatt/vim-fswitch.git' # switching between companion source files (e.g. .h and .cpp)
[[plugins]]
repo = 'janko-m/vim-test.git' # easy testing for various langs
[[plugins]]
repo = 'Shougo/neco-vim' # modern vim autocomplete
[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent' # python autoindent pep8 compatible
[[plugins]]
repo = 'racer-rust/vim-racer' # racer support
[[plugins]]
repo = 'marijnh/tern_for_vim' # tern for vim
[[plugins]]
repo = 'Shougo/echodoc.vim' # print documents in echo area
[[plugins]]
repo = 'apalmer1377/factorus' # refactoring tool
# --[ LaTeX ]-----------------------------------------------------------------------------
[[plugins]]
repo = 'donRaphaco/neotex'
# ----------------[  Tags  ]--------------------------------------------------------------
[[plugins]]
repo = 'yuki777/gtags.vim.git' # Gtags v0.64
[[plugins]]
repo = 'bbchung/gasynctags.git' # autogenerate gtags to cscope db
[[plugins]]
repo = 'neg-serg/gtags-cscope-vim' #  my gtags-cscope fork
# ---------------[ Misc syntax ]----------------------------------------------------------
[[plugins]]
repo = 'tpope/vim-markdown' # markdown vim mode
[[plugins]]
repo = 'mzlogin/vim-markdown-toc' # plugin to autogenerate table of contents for markdown
[[plugins]]
repo = 'sheerun/vim-polyglot' #  language pack collection
[[plugins]]
repo = 'whatyouhide/vim-gotham' # gotham colorscheme for nvim
[[plugins]]
repo = 'joshdick/onedark.vim' # onedark colorscheme
[[plugins]]
repo = 'KeitaNakamura/neodark.vim' # neodark colorscheme
[[plugins]]
repo = 'NLKNguyen/papercolor-theme' # great bright colorscheme
[[plugins]]
repo = 'icymind/NeoSolarized' # solarized with better neovim support
[[plugins]]
repo = 'arcticicestudio/nord-vim'  # dark and cold colorscheme
[[plugins]]
repo = 'chriskempson/base16-vim' # base16 colorschemes pack
[[plugins]]
repo = 'tyrannicaltoucan/vim-deep-space' # deepspace colorscheme
[[plugins]]
repo = 'bluz71/vim-moonfly-colors' # moonfly colorscheme
[[plugins]]
repo = 'ryanoasis/vim-devicons.git' # fancy icons for fonts
# --[ dcvs ]------------------------------------------------------------------------------
[[plugins]]
repo = 'tpope/vim-fugitive.git' # Git stuff. Needed for powerline etc
[[plugins]]
repo = 'idanarye/vim-merginal.git' # to handle branches/megge conflicts
[[plugins]]
repo = 'junegunn/gv.vim' # yet another git commit browser
[[plugins]]
repo = 'airblade/vim-gitgutter.git' # show last git changes
[[plugins]]
repo = 'gregsexton/gitv' # gitk for vim
# --[ Tmux ]----------------------------------------------------------------------------
[[plugins]]
repo = 'christoomey/vim-tmux-navigator' # easy jump between windows
#--[ Session ]--------------------------------------------------------------------------
[[plugins]]
repo = 'xolox/vim-misc' # for vim-session
merged = 0
[[plugins]]
repo = 'xolox/vim-session' # rule sessions
depends = 'vim-misc'
merged = 0
# --[ Misc ]----------------------------------------------------------------------------
[[plugins]]
repo = 'powerman/vim-plugin-ruscmd' # prevent too much ru-en layout switching with c-s
[[plugins]]
repo = 's3rvac/AutoFenc' #  try to autodelect filetype
[[plugins]]
repo = 'wellle/targets.vim' # better text objects
[[plugins]]
repo = 'Konfekt/FastFold' # Do not update folds when it's not needed
[[plugins]]
repo = 'vim-scripts/ViewOutput.git' # VO commandline output
[[plugins]]
repo = 'jamessan/vim-gnupg.git' # Transparent work with gpg-encrypted files
[[plugins]]
repo = 'Yggdroot/indentLine' # indentlines
[[plugins]]
repo = 'Shougo/deol.nvim' # better neovim terminal-based mode
[[plugins]]
repo = 'itchyny/vim-parenmatch' #  An efficient alternative to the standard matchparen plugin
[[plugins]]
repo = 'haya14busa/dein-command.vim' # dein commands
[[plugins]]
repo = 'mopp/autodirmake.vim.git' # automake dir which didnt exists
