# --[ Main ]-------------------------------------------------------------------------------
[[plugins]]
repo = 'Shougo/neoinclude.vim' # include completion framework for neocomplete/deoplete
on_i = 1
# --[ Edit ]-------------------------------------------------------------------------------
[[plugins]]
repo = 'simnalamburt/vim-mundo' # undo tree
on_cmd = 'MundoToggle'
[[plugins]]
repo = 'godlygeek/tabular.git' # for tabularizing
on_cmd = 'Tabularize'
[[plugins]]
repo = 'ntpeters/vim-better-whitespace' # find whitespaces with ease
on_cmd = 'StripWhitespace'
# --[ Web ]-------------------------------------------------------------------------------
[[plugins]]
repo = 'mattn/emmet-vim' # expanding abbreviations similar to emmet
on_cmd = ['EmmetInstall']
# --[ Markdown ]--------------------------------------------------------------------------
[[plugins]]
repo = 'iamcco/markdown-preview.vim' # markdown preview
on_ft = ['markdown']
[[plugins]]
repo = 'iamcco/mathjax-support-for-mkdp' # mathjax support for markdown preview
on_ft = ['markdown']
# --[ JS ]---------------------------------------------------------------------------------
[[plugins]]
repo = 'maksimr/vim-jsbeautify' # neoformat formatter ;)
on_ft = ['javascript']
# --[ Python ]-----------------------------------------------------------------------------
[[plugins]]
repo = 'vim-scripts/IndentConsistencyCop.git' # autochecks for indent
on_ft = ['python']
# --[ Rust ]-------------------------------------------------------------------------------
[[plugins]]
repo = 'rust-lang/rust.vim' # detection of rust files
on_ft = ['rust']
merged = 1
[[plugins]]
repo = 'jtdowney/vimux-cargo' # rust-cargo bindings
[[plugins]]
# --[ Haskell ]-----------------------------------------------------------------------------
[[plugins]]
repo = 'bitc/vim-hdevtools' # type-related features
on_ft = ['haskell']
[[plugins]]
repo = 'neovimhaskell/haskell-vim' # syntax highlight and indentation
on_ft = ['haskell']
# --[ Ruby ]--------------------------------------------------------------------------------
[[plugins]]
repo = 'osyo-manga/vim-monster' # alternative ruby autocompletion
on_ft = ['ruby']
[[plugins]]
repo = 'tpope/vim-rails.git' # rails plugin from Tim Pope
on_ft = ['ruby']
[[plugins]]
repo = 'tpope/vim-rake.git' # ruby rake support
on_ft = ['ruby']
[[plugins]]
repo = 'tpope/vim-rbenv.git' # ruby rbenv support
on_ft = ['ruby']
# --[ Perl ]--------------------------------------------------------------------------------
[[plugins]]
repo = 'vim-perl/vim-perl' # perl support
on_ft = ['perl']
[[plugins]]
repo = 'c9s/perlomni.vim' # perl omnicomplete
on_ft = ['perl']
# --[ Go ]-----------------------------------------------------------------------------------
[[plugins]]
repo = 'jstemmer/gotags.git' # tags for go
on_ft = ['go']
# --[ Misc Langs ]--------------------------------------------------------------------------
[[plugins]]
repo = 'joonty/vdebug' #  Multi-language DBGP debugger client for Vim (PHP, Python, Perl, Ruby, etc.
on_cmd = ['VdebugStart']
[[plugins]]
repo = 'oscarh/vimerl' # vim erlang support
on_ft = ['erlang']
[[plugins]]
repo = 'rhysd/vim-crystal' # crystal language support
on_ft = ['crystal']
[[plugins]]
repo = 'jalvesaq/Nvim-R' # nvim R support
on_ft = 'R'
[[plugins]]
repo = 'nosami/Omnisharp.git' # omnisharp completion
on_ft = 'csharp'
# --[ Misc syntax ]-----------------------------------------------------------------------
[[plugins]]
repo = 'blindFS/vim-regionsyntax' #  region syntax highlighting
on_ft = ['vimwiki', 'markdown', 'tex', 'html']
[[plugins]]
repo = 'baskerville/vim-sxhkdrc' # sxhkd config syntax
on_ft = ['sxhkdrc']
