local na = "🌐  "

return { { "Afrikaans", "af", "🇦🇫" }, { "Albanian", "sq", "🇦🇱" }, { "Amharic", "am", "🇦🇲" },
  { "Arabic", "ar", "🇸🇦" }, { "Armenian", "hy", "🇦🇲" }, { "Azerbaijani", "az", "🇦🇿" },
  { "Basque", "eu", na }, { "Belarusian", "be", "🇧🇾" }, { "Bengali", "bn", "🇧🇳" },
  { "Bosnian", "bs", "🇧🇦" }, { "Bulgarian", "bg", "🇧🇬" }, { "Catalan", "ca", "🇪🇸" },
  { "Cebuano", "ceb", "🇵🇭" }, { "Chinese (Simplified)", "zh-CN", "🇨🇳" },
  { "Chinese (Traditional)", "zh-TW", "🇨🇳" }, { "Corsican", "co", "🇨🇴" },
  { "Croatian", "hr", "🇭🇷" }, { "Czech", "cs", "🇨🇿" }, { "Danish", "da", "🇩🇰" },
  { "Dutch", "nl", "🇳🇱" },
  { "English", "en", "🇬🇧" }, { "Esperanto", "eo", "🇪🇺" }, { "Estonian", "et", "🇪🇪" },
  { "Finnish", "fi", "🇫🇮" }, { "French", "fr", "🇫🇷" }, { "Frisian", "fy", na },
  { "Galician", "gl", "🇬🇱" }, { "Georgian", "ka", "🇬🇪" }, { "German", "de", "🇩🇪" },
  { "Greek", "el", "🇬🇷" }, { "Gujarati", "gu", "🇬🇺" }, { "Haitian Creole", "ht", "🇭🇹" },
  { "Hausa", "ha", na }, { "Hawaiian", "haw", na }, { "Hebrew", "iw", "🇮🇱" },
  { "Hindi", "hi", "🇮🇳" }, { "Hmong", "hmn", "🇨🇳" }, { "Hungarian", "hu", "🇭🇺" },
  { "Icelandic", "is", "🇮🇸" }, { "Igbo", "ig", na }, { "Indonesian", "id", "🇮🇩" },
  { "Irish", "ga", "🇮🇪" }, { "Italian", "it", "🇮🇹" }, { "Japanese", "ja", "🇯🇵" },
  { "Javanese", "jw", na }, { "Kannada", "kn", "🇰🇳" }, { "Kazakh", "kk", "🇰🇿" },
  { "Khmer", "km", "🇰🇲" }, { "Korean", "ko", "🇰🇷" }, { "Kurdish", "ku", "🏴 󠁩󠁲󠀱󠀶󠁿" },
  { "Kyrgyz", "ky", "🇰🇬" },
  { "Lao", "lo", "🇱🇦" }, { "Latin", "la", na }, { "Latvian", "lv", "🇱🇻" }, { "Lithuanian", "lt", "🇱🇹" },
  { "Luxembourgish", "lb", "🇱🇺" }, { "Macedonian", "mk", "🇲🇰" }, { "Malagasy", "mg", "🇲🇬" },
  { "Malay", "ms", "🇲🇸" }, { "Malayalam", "ml", "🇲🇱" }, { "Maltese", "mt", "🇲🇹" },
  { "Maori", "mi", "🇳🇿" }, { "Marathi", "mr", "🇲🇷" }, { "Mongolian", "mn", "🇲🇳" },
  { "Myanmar (Burmese)", "my", "🇲🇲" }, { "Nepali", "ne", "🇳🇵" }, { "Norwegian", "no", "🇳🇴" },
  { "Nyanja (Chichewa)", "ny", na }, { "Pashto", "ps", "🇵🇸" }, { "Persian", "fa", "🇫🇦" },
  { "Polish", "pl", "🇵🇱" }, { "Portuguese (Portugal, Brazil)", "pt", "🇵🇹" }, { "Punjabi", "pa", "🇮🇳" },
  { "Romanian", "ro", "🇷🇴" }, { "Russian", "ru", "🇷🇺" }, { "Samoan", "sm", "🇼🇸" },
  { "Scots Gaelic", "gd", "🏴  󠁧󠁢󠁳󠁣󠁴󠁿󠁧󠁢󠁳󠁣󠁴󠁿" }, { "Serbian", "sr", "🇸🇷" },
  { "Sesotho", "st", "🇸🇹" },
  { "Shona", "sn", "🇸🇳" }, { "Sindhi", "sd", "🇸🇩" }, { "Sinhala (Sinhalese)", "si", "🇸🇮" },
  { "Slovak", "sk", "🇸🇰" }, { "Slovenian", "sl", "🇸🇱" }, { "Somali", "so", "🇸🇴" },
  { "Spanish", "es", "🇪🇸" }, { "Sundanese", "su", na }, { "Swahili", "sw", na },
  { "Swedish", "sv", "🇸🇻" }, { "Tagalog (Filipino)", "tl", "🇹🇱" }, { "Tajik", "tg", "🇹🇬" },
  { "Tamil", "ta", "🇹🇦" }, { "Telugu", "te", na }, { "Thai", "th", "🇹🇭" }, { "Turkish", "tr", "🇹🇷" },
  { "Ukrainian", "uk", "🇺🇦" }, { "Urdu", "ur", na }, { "Uzbek", "uz", "🇺🇿" },
  { "Vietnamese", "vi", "🇻🇳" }, { "Welsh", "cy", "🇨🇾" }, { "Xhosa", "xh", na },
  { "Yiddish", "yi", na }, { "Yoruba", "yo", "🇿🇦" }, { "Zulu", "zu", na } }

local translate = require("configs.translate")
map("n", "<leader>t", translate, remap)
map("v", "<leader>t", translate, remap)
