#!/usr/bin/env dash
# Switch to US international with Caps as Mod/Escape
sudo localectl set-x11-keymap "us,ru" altgr-intl "" grp:alt_shift_toggle,grp:alt_shift_toggle,grp_led:scroll,ctrl:nocaps,compose:ralt,pointerkeys
unclutter --fork --timeout 1 --jitter 50 --ignore-scrolling
