#!/usr/bin/env dash
# Switch to US international with Caps as Mod/Escape
localectl set-x11-keymap us,ru "" altgr-intl 'keypad:pointerkeys,ctrl:nocaps'
unclutter --fork --timeout 1 --jitter 50 --ignore-scrolling
