#!/usr/bin/env dash
export ENV=$HOME/.profile
xrdb -merge "$HOME/.Xresources"
xset s off -dpms
sudo openrgb --server -p neg.orp &
eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK
exec /usr/bin/i3-gnome
