#!/bin/dash
export ENV=$HOME/.profile
xrdb -I$XDG_CONFIG_HOME/xres -load "$HOME/.Xresources"
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK
export XDG_CURRENT_DESKTOP=GNOME
xrandr -s 3840x2160 -r 120
exec i3
# vim: set ftype=sh
