#!/usr/bin/env dash
setxkbmap -layout 'us,ru' -option 'grp:lalt_lshift_toggle,ctrl:nocaps,pointerkeys' -variant altgr-intl -model pc104
pkill unclutter; unclutter --fork --timeout 1 --jitter 50 --ignore-scrolling
