#!/bin/bash

function gen_workspaces() {
    i3-msg -t get_workspaces | \
        tr ',' '\n' | \
        grep "name" | \
        sed 's/"name":"\(.*\)"/\1/g' | \
        sort -n
}

ws=$( (echo empty; gen_workspaces)  | rofi -columns 8 -lines 2 -dmenu -p "Select workspace:")
[[ -n "${ws}" ]] && i3-msg workspace "${ws}"
