#!/bin/dash
# thx to https://copyninja.info/blog/email_setup.html
MDIR="insales gmail"
mbsync -a
notmuch new

for mdir in $MDIR; do
    for fdir in $(ls -d /home/neg/.local/mail/$mdir/*); do
      if [ $(basename $fdir) != "INBOX" ]; then
          notmuch tag +$(basename $fdir) -inbox -- folder:$mdir/$(basename $fdir)
          notmuch tag +$mdir-$(basename "$fdir") -inbox -- folder:$mdir/$(basename $fdir)
      fi
    done
done
