#!/bin/dash
. $ENV

cache="$HOME/tmp"
ff="$cache/sxiv.$$"
tmp_wall="$cache/wall_sxiv.$$"
z="$XDG_DATA_HOME/sxiv/data"
last="$XDG_DATA_HOME/sxiv/last"
trash="$HOME/trash/1st-level/pic"
rofi_cmd="rofi -dmenu -sort -matching fuzzy -no-plugins -no-only-match -theme sxiv -custom"

rotate() {
    while read file; do mogrify -rotate "$1" "$file"; done
}

proc() {
    cmd="$1"
    tee "$ff"
    if [ -z "$dest" ]; then
        dest=$(_FASD_DATA="$z" fasd -tlR \
            | sed 's:^'$HOME':~:' \
            | $rofi_cmd -p "⟬$cmd⟭ ❯>"  \
            | sed 's:^~:'$HOME':')
    fi
    [ -z "$dest" ] && exit 0
    if [ -d "$dest" ]; then
        while read line; do
            $cmd "$(realpath $line)" $dest
        done < "$(realpath "$ff")"
        _FASD_DATA="$z" fasd -RA "$dest"
        printf "%s\n" "$cmd \"$dest\"" > "$last"
    else
        _FASD_DATA="$z" fasd -D "$dest"
    fi
    trap finish EXIT
}

repeat_action() {
    tee "$ff"
    fname="$(realpath $(cat "$ff"))"
    last="$(cat "$last" | xargs)"
    cmd=$(echo $last | awk '{print $1}')
    dest=$(echo $last | awk '{print $2}')
    if [ $cmd = 'mv' ] || [ $cmd = 'cp' ]; then
        $cmd "$fname" "$dest"
    fi
    trap finish EXIT
}

copy_name() {
    tee "$ff"
    fname="$(realpath "$(cat "$ff")")"
    echo "$fname" | xsel -bi
    ~/bin/scripts/pic_notify "$fname"
    trap finish EXIT
}

wall() {
    action="$1"
    wallarg=""
    specarg=""
    case $action in
        center) wallarg="-center" ;;
        tile) wallarg="-tile" ;;
        fill) wallarg="-fill" ;;
        full) wallarg="-full" ;;
        cover) wallarg="-full" ;;
        mono) specarg="plus"
    esac
    tee "$tmp_wall"
    if [ -z $specarg ]; then
        while read wall; do
            hsetroot $wallarg "$wall" &
        done < "$tmp_wall"
    else
        while read wall; do
            convert "$wall" -colors 2 "$cache/__$(basename $wall)"
            hsetroot -full "$cache/__$(basename $wall)"
            rm "$cache/__$(basename $wall)"
        done < "$tmp_wall"
    fi
}

finish() {
    rm -f "$ff" "$ff"
}

case "$1" in
    "C-comma") rotate 270 ;;
    "C-less") rotate -90 ;;
    "C-period") rotate 90 ;;
    "C-slash") rotate 180 ;;
    "c") copy_name ;;
    "r") repeat_action ;;
    "v") proc mv ;;
    "C-c") proc cp ;;
    "C-d") dest="$HOME/trash/1st-level/pic"  proc mv ;;
    "C-1") wall "full" ;;
    "C-2") wall "mono" ;;
    "C-3") wall "center" ;;
    "C-4") wall "tile" ;;
    "C-5") wall "fill" ;;
    "C-w") wall "cover" ;;
esac
